# tf-manage2 configuration file
# For documentation, see: https://github.com/sorinlg/tf-manage2

config_version: "2.0"
repo_name: tfm-project
env_rel_path: terraform/environments
module_rel_path: terraform/modules
